version: '3'

services:
  backend:
    build: ./backend
    container_name: backend

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/self-signed:/etc/nginx/self-signed:ro
    depends_on:
      - backend
